[package]
name = "gut-time"
version = "0.1.0"
authors = ["Jared De La Cruz <jared@jareddlc.com>"]
edition = "2018"

[lib]
name = "gut_time"
crate-type = ["cdylib"]

[dependencies]
gut-plugin = "0.1"

[profile.release]
codegen-units = 1
opt-level = 'z'
lto = true
