[package]
name = "gut-time"
version = "0.1.0"
authors = ["Jared De La Cruz <jared@jareddlc.com>"]
edition = "2018"

# building:
# cargo build --target wasm32-wasi --release

[lib]
name = "gut_time"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = 'z'
lto = true
