name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add target
      run: rustup target add wasm32-wasi
    - name: Build
      run: cargo build --verbose --target wasm32-wasi --release
    - name: Release
      uses: anton-yurchenko/git-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALLOW_EMPTY_CHANGELOG: true
      with:
        args: target/wasm32-wasi/release/gut_time.wasm
